input {
  # Logstash écoute les données envoyées par Filebeat sur le port 5044
  beats {
    port => 5044
  }
}

filter {
  # Ici, on pourrait ajouter des filtres pour trier les logs plus tard
}

output {
  # Logstash envoie les résultats à Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "log-interne-%{+YYYY.MM.dd}"
  }
  
  # Optionnel : affiche aussi les logs dans le terminal de Docker pour débugger
  stdout { codec => rubydebug }
}