events {}

http {
    server {
        listen 80;

        # Redirection /api → API interne
        location /api/ {
            proxy_pass http://api:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Optionnel : rediriger tout le reste vers ton front
        location / {
            proxy_pass http://web:80/;
        }
    }
}
