FROM postgres:16

# Définir les variables d’environnement
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=Gougougagaklemdpdefoula
ENV POSTGRES_DB=EdfDb

# (Optionnel) Copier des scripts d'init (SQL ou .sh)
# Ils seront exécutés automatiquement au premier démarrage
# COPY ./init/*.sql /docker-entrypoint-initdb.d/

# Exposer le port Postgres
EXPOSE 5432
