# dhcpd.conf pour DMZ (Statique et Sécurisé)
authoritative;
default-lease-time 600;
max-lease-time 7200;

subnet 192.168.100.0 netmask 255.255.255.0 {
  # Pas de 'range' pour éviter que des machines inconnues 
  # ne reçoivent une IP en DMZ.

  # Réservation pour ton API ou Serveur
  host api_service {
    hardware ethernet 00:00:00:00:00:01; # MAC à adapter
    fixed-address 192.168.100.10;
  }
}